#修改TNAME: MI-4中的MI-4为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build  Padavan

on: 
  workflow_dispatch:
    inputs:
      firmwarever:
        description: 'firmware''s version'
        required: true
        default: '20201015'
      busyboxver:
        type: choice
        description: 'busybox''s version'
        options:
        - 1.24.x
        - 1.34.1
        default: '1.24.x'
      ssp:
        type: boolean
        description: 'whether to apply the patch for download ssp bin from local or remote url'
        default: 'false'
      uploadwet:
        type: boolean
        description: 'whether to upload firmware to wetransfer'
        default: 'false'
      pushplus:
        type: boolean
        description: 'whether to notify through pushplus'
        default: 'false'
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [B70, MI-4]
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2.3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/keke1023/padavan-4.4.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/   
      - name: Start Build
        run: |
          make ${{ inputs.target }}
          echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.target }}-${{ env.TAG_ANME }}
          path: trunk/images/*.trx
      - uses: ncipollo/release-action@v1
        if: github.event.inputs.release == 'true'
        with:
          commit: ${{ github.sha }}
          tag: Padavan
          artifacts: trunk/images/*.trx
          allowUpdates: true
